services:
    mysql:
        build:
            context: .
            dockerfile: docker/mysql/Dockerfile
        container_name: reminder-mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: reminder_db
            TZ: Asia/Shanghai
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
